### ISSUE TITLE
WorldEdit incompatibility.

### ISSUE THREAD

**Issue by tserversbfs** [lovexyn0827/Chunkmap#2]
Running MC 1.17.1 Tried two versions of this mod with and without worldedit. Fatal error.

[16:00:07] [main/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformsRegisteredEvent@8a214938 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-mod-7.2.7.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-mod-7.2.7.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-mod-7.2.7.jar:?]
	at com.sk89q.worldedit.fabric.FabricWorldEdit.registerCommands(FabricWorldEdit.java:157) ~[worldedit-mod-7.2.7.jar:?]
	at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:41) ~[fabric-command-api-v1-1.1.4+cf39a74318-1bce54f6903ba590.jar:?]
	at net.minecraft.class_2170.handler$zgm000$fabric-command-api-v1$fabric_addCommands(class_2170.java:1047) [server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:235) [server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:39) [server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:88) [server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:147) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.17.1-loader.0.14.19-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.UnsatisfiedLinkError: Failed to load library "/opt/java/openjdk/lib/libawt_xawt.so"
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.System.loadLibrary(Unknown Source) ~[?:?]
	at java.awt.Toolkit$2.run(Unknown Source) ~[?:?]
	at java.awt.Toolkit$2.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at java.awt.Toolkit.loadLibraries(Unknown Source) ~[?:?]
	at java.awt.Toolkit.initStatic(Unknown Source) ~[?:?]
	at java.awt.Toolkit.<clinit>(Unknown Source) ~[?:?]
	at sun.awt.AppContext$2.run(Unknown Source) ~[?:?]
	at sun.awt.AppContext$2.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at sun.awt.AppContext.initMainAppContext(Unknown Source) ~[?:?]
	at sun.awt.AppContext$3.run(Unknown Source) ~[?:?]
	at sun.awt.AppContext$3.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at sun.awt.AppContext.getAppContext(Unknown Source) ~[?:?]
	at javax.imageio.spi.IIORegistry.getDefaultInstance(Unknown Source) ~[?:?]
	at javax.imageio.ImageIO.<clinit>(Unknown Source) ~[?:?]
	at com.sk89q.worldedit.util.asset.ImageHeightmapLoader.getAllowedExtensions(ImageHeightmapLoader.java:53) ~[worldedit-mod-7.2.7.jar:?]
	at com.sk89q.worldedit.util.asset.AssetLoaders.registerAssetLoader(AssetLoaders.java:85) ~[worldedit-mod-7.2.7.jar:?]
	at com.sk89q.worldedit.util.asset.AssetLoaders.init(AssetLoaders.java:75) ~[worldedit-mod-7.2.7.jar:?]
	at com.sk89q.worldedit.extension.platform.Capability$2.initialize(Capability.java:55) ~[worldedit-mod-7.2.7.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.choosePreferred(PlatformManager.java:193) ~[worldedit-mod-7.2.7.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlatformsRegistered(PlatformManager.java:319) ~[worldedit-mod-7.2.7.jar:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-mod-7.2.7.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-mod-7.2.7.jar:?]
	... 14 more
[16:00:07] [main/FATAL]: Failed to start the minecraft server
com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting USER_COMMANDS
	at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:175) ~[worldedit-mod-7.2.7.jar:?]
	at com.sk89q.worldedit.fabric.FabricWorldEdit.registerCommands(FabricWorldEdit.java:159) ~[worldedit-mod-7.2.7.jar:?]
	at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:41) ~[fabric-command-api-v1-1.1.4+cf39a74318-1bce54f6903ba590.jar:?]
	at net.minecraft.class_2170.handler$zgm000$fabric-command-api-v1$fabric_addCommands(class_2170.java:1047) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:235) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:88) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:147) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.17.1-loader.0.14.19-launcher.0.11.2.jar:0.11.2]
2023/04/21 16:00:17 Stopping with rcon-cli

**Comment by lovexyn0827** [comment]
It seems that AWT is not supported on your server, but currently the mod require it to work. Trying another Java runtime might be a solution if the system does support GUI.

And in this summer, several other renderers will be introduced to solve this problem.

**Comment by tserversbfs** [comment]
What is AWT? Which mod requires it to work? My java version is java17-openj9 running in docker with the image as image: itzg/minecraft-server:java17-openj9

and to clarify... I got the mod to work, but not with WorldEdit installed. Also, WorldEdit works, but not with Chunkmap installed.

**Comment by lovexyn0827** [comment]
A1: AWT is a component of the Java runtime environment which supports creating GUI on Java.
A2: Chunkmap requires it to work and WorldEdit seems to  require it to load images.

I have tried to run the server with the following configurations: 
- Windows 7
- Jetbean Runtime 17.0.2 / oracle jdk-16.0.1_windows-x64_bin
- Minecraft dedicated server 1.17.1
- fabric-api-0.37.0+1.17
- worldedit-mod-7.2.7
- chunkmap-1.17-1.19-20230404
- fabric-carpet-1.17.1-1.4.44+v210714

Given that the server can run with only one of the mods,and the server can be started successfully on Jetbean Runtime 17 () even with both of these mods installed, I think the AWT on the server is fine, but unable to be loaded fo some reason when these mods coexist on some specific platforms. 

However, I have to apologize for that I don't know exactly what caused the issue and how to resolve it currently. 

But anyway, according to the console output, please check if the file /opt/java/openjdk/lib/libawt_xawt.so exists. If it doesn't exist or has been damaged, reinstalling the Java Runtime or trying another Java may help.
